---
- name: Configure jumpbox from fresh install
  hosts: jumpboxes
  become: yes
  vars:
    jumpbox: yes
    created_user: ansible
    nginx_user: nginx
    nginx_group: nginx
    nest1_ip: 192.168.122.110
    nest1_port: 80
    nest2_ip: 192.168.122.173
    nest2_port: 80

  roles:
    - initial-setup
    - nginx

  post_tasks:
    - debug:
        msg: "Initial setup for jumpbox complete"

  handlers:
    - include: handlers/main.yml
