---
- name: Configure nests for Nginx
  hosts: nests
  vars:
    ansible_user: ansible
    nginx_user: nginx
    nginx_group: nginx
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
    nests: yes

  roles:
    - nginx

  post_tasks:
    - debug:
        msg: "Nginx setup for nests complete"

  handlers:
    - include: handlers/main.yml