---
- hosts: all
  vars:
    created_user: ansible
    nginx_user: nginx
    nginx_group: nginx
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
  roles:
    - { role: initial-setup, become: yes}
    - nginx